### ISSUE TITLE
Maybe add some of the references to tooling

### ISSUE THREAD

**Issue by springcoil** [ianozsvald/data_science_delivered#1]
Hi Ian,
Maybe add www.yhathq.com and www.sense.io to the list for 'deployment platforms'. 

But I think what you have is fine as it is

**Comment by ianozsvald** [comment]
I've added both - have you used sense.io? Any strengths/weaknesses for both I should note?

**Comment by springcoil** [comment]
Hi Ian,
I haven't used sense enough to note strengths and weaknesses

On Wed, Oct 14, 2015 at 5:06 PM, Ian Ozsvald notifications@github.com
wrote:

> I've added both - have you used sense.io? Any strengths/weaknesses for
> both I should note?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ianozsvald/data_science_delivered/issues/1#issuecomment-148078541
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by ianozsvald** [comment]
cheers. I kept yhathq (and I'll link to your pyconireland talk if you're still talking about it - send me a link when this is online) but dropped sense.io (I only want stuff that's known-good in this doc).
